name: Approve

on:
  pull_request:
    types: [labeled]

jobs:
  approve:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: >-
      ${{
        github.event.label.name == 'Skip Review' &&
        github.event.pull_request.user.login == 'Issiki0416'
      }}
    env:
      NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Approve
        run: gh pr review ${{ env.NUMBER }} --approve
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
